name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checar o código
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for backend
        run: |
          IMAGE="${{ secrets.DOCKER_USERNAME }}/backend:latest"
          docker build -t "$IMAGE" -f backend/Dockerfile backend
          docker push "$IMAGE"

      - name: Run tests inside Docker container
        run: |
          IMAGE="${{ secrets.DOCKER_USERNAME }}/backend:latest"
          docker run --rm "$IMAGE" npm run test

      - name: Build project
        run: |
          IMAGE="${{ secrets.DOCKER_USERNAME }}/backend:latest"
          docker run --rm "$IMAGE" npm run build

      - name: Deploy to production (exemplo com Docker)
        run: |
          IMAGE="${{ secrets.DOCKER_USERNAME }}/backend:latest"
          docker run --rm "$IMAGE"

